\input texinfo
@documentlanguage en
@settitle loara-cfggen
@copying
Copyright @copyright{} 2024 Paolo De Donato

@quotation
This file is part of limine-genconf.

limine-genconf is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

limine-genconf is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with Foobar. If not, see <https://www.gnu.org/licenses/>. 
@end quotation
@end copying

@titlepage
@title loara-cfggen

@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@contents
@node Top
@top limine-cfggen

Automatically updates Blake2b hashes in Limine configuration files

@menu

* NAME:: The program name
* AUTHOR:: Author

@end menu

@node NAME
@chapter NAME

loara-cfggen - Update hashes in Limine configuration files

@node AUTHOR
@chapter AUTHOR

Paolo De Donato

@bye
